apiVersion: v1
kind: Pod
metadata:
  name: broken-pod-3
spec:
  containers:
  - name: myapp
    image: b4xim/nodeapp:v1
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "250m"